version: '3'
services:
  api-heroes:
    # build: .
    image: efillipi/api-herois:v1
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb

    depends_on: 
      - mongodb
    links: 
       - mongodb
        
  mongodb:
    image: mongo
    ports:
      - 27017:270173